run-title: TwoStep_4
save-path: ckpt
save-interval: 5000

task:
  common-prob: 0.8
  reward-prob: 0.9
  swtich-prob: 0.025

  train-episodes: 20_000
  trials-per-epi: 100
  test-episodes: 300

a2c:
  mem-units: 48
  
  val-loss-weight: 0.05
  entropy-weight: 0.05
  max-grad-norm: 999
  
  gamma: .90
  lr: 7.e-4
  weight-decay: 0

